import Head from "next/head";
import Image from "next/image";
import { Inter, Tourney } from "next/font/google";
import MainLayout from "@/components/layouts/MainLayout";
import Slider from "react-slick";
import HoiAn from "@assets/images/hoi-an.png";
import Banner from "@assets/images/banner.png";
import TopBar from "@/components/common/TopBar";
import HomeBanner from "@/components/common/HomeBanner";

export default function Home() {
  var settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    focusOnSelect: true,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <HomeBanner/>
        
        {/* <div>
          <div style={{width: "40%"}}>
            <Image src={Banner} alt="" />
          </div>
          <div style={{width: "40%"}}>
            <Image src={Banner} alt="" />
          </div>
        </div> */}
      </MainLayout>
    </>
  );
}
