import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";
import HomeBanner from "@/components/common/HomeBanner";
import HomePromotion from "@/components/common/HomePromotion";
import HomeDestinations from "@/components/common/HomeDestinations";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <HomeBanner/>
        <HomePromotion/>
        {/* <HomeDestinations/> */}
        
      </MainLayout>
    </>
  );
}
