import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";
import {
  HomeBanner,
  HomePromotion,
  HomeDestinations,
} from "@/modules/HomePage";
import HomeTours from "@/modules/HomePage/HomeTours";
import SupplierLayout from "@/components/layouts/SupplierLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {true ? (
        <MainLayout>
          <HomeBanner />
          <HomePromotion />
          <HomeDestinations />
          <HomeTours />
        </MainLayout>
      ) : (
        <SupplierLayout />
      )}
    </>
  );
}
