import { ITour } from "@/types/services/tour";

const Mock_Data_Tours: ITour[] = [
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "Hà Nội",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
  {
    id: "1",
    name: "Hạ Long - Sửng Sốt - Titop 2 ngày 1 đêm",
    bannerUrl:
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    imageUrls: [
      "https://firebasestorage.googleapis.com/v0/b/every-weekend-web.appspot.com/o/banner_halong.jpg?alt=media&token=ea5d21e9-cc50-4ea6-a4d7-1c0119cd3944",
    ],
    quantity: 20,
    price: 2450000,
    discount: 15,
    favoriteNumber: 132,
    destinationId: "1",
    departure: "ha noi",
    dayTime: 2,
    supplierId: "1",
    startTime: 1696950000,
    concentrationTime: 1696946400,
    vehicle: "xe máy",
    sightseeing:
      "Đảo Titop, Hang Luồn, Hang Sửng Sốt, Chợ đêm Hạ Long, Bãi Cháy",
    cuisine: "mực, cá",
    hotelId: "1",
    suitablePerson: "all",
    highlight: "du thuyền",
    schedule: "lịch trình",
    tourGuideId: "1",
  },
];

export { Mock_Data_Tours };
